language: ruby
rvm:
  - "2.3.1"
  - "2.2.5"
script: COVERAGE=true CODECLIMATE_REPO_TOKEN=1a209f56ee0cdf880825ab5d6a414ccb866d1cdf55ff1530574b018382ccf263 bundle exec rake
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - "echo 'gem: --no-document --no-rdoc' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.yml-travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
