language: ruby
rvm:
  - "2.3.0"
script: bundle exec rake
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml-example config/database.yml
  - psql -c 'create database eldac_test;' -U eldac
